@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NjJkZjNjZC00MTU4LTQ0MjUtYjQzYy1jNDAwOGM0YWRlNzgiLCJleHAiOjE3ODE4Mzc2MDh9.k3ZDWwsAt7heTzix_OZnyi7dKL_nVVd66XuIu7x_dak

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Get my profile
GET http://localhost:8000/users/me
Authorization: Bearer {{token}}

### Update profile
PATCH http://localhost:8000/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bio": "Hello I am a dev"
}