"""add joined_at to room_members

Revision ID: 332e77487b9d
Revises: fb2221adbfaf
Create Date: 2026-06-19 22:20:00.995774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332e77487b9d'
down_revision: Union[str, Sequence[str], None] = 'fb2221adbfaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_members', 'joined_at')
    # ### end Alembic commands ###
