"""add role to room_members and is_admin to users

Revision ID: 9be18c1cad4e
Revises: f5fdb17a719d
Create Date: 2026-06-19 03:48:31.711252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be18c1cad4e'
down_revision: Union[str, Sequence[str], None] = 'f5fdb17a719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    roomrole = sa.Enum('member', 'admin', name='roomrole')
    roomrole.create(op.get_bind())    
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('role', sa.Enum('member', 'admin', name='roomrole'), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('room_members', 'role')
    # ### end Alembic commands ###
