"""fix file_uploads room_id foreign key

Revision ID: dda404d9a171
Revises: 332e77487b9d
Create Date: 2026-06-20 04:09:26.986857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda404d9a171'
down_revision: Union[str, Sequence[str], None] = '332e77487b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_file_uploads_room_id_users'), 'file_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('fk_file_uploads_room_id_rooms'), 'file_uploads', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_file_uploads_room_id_rooms'), 'file_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('fk_file_uploads_room_id_users'), 'file_uploads', 'users', ['room_id'], ['id'])
    # ### end Alembic commands ###
