"""add thumbnail_path to file_uploads

Revision ID: ebc60beebc08
Revises: dda404d9a171
Create Date: 2026-06-21 13:16:56.331410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc60beebc08'
down_revision: Union[str, Sequence[str], None] = 'dda404d9a171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('thumbnail_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'thumbnail_path')
    # ### end Alembic commands ###
