"""add avatar_url to rooms

Revision ID: fb2221adbfaf
Revises: 9be18c1cad4e
Create Date: 2026-06-19 21:01:42.742285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2221adbfaf'
down_revision: Union[str, Sequence[str], None] = '9be18c1cad4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'avatar_url')
    # ### end Alembic commands ###
